mesto-co/core

.github/CODEOWNERS
.. от текущей команды @mesto-co/architects - @ak239 и @skuznetsov
=> infra(pr): CODEOWNERS файл, чтобы обеспечить минимум одно review ..

config.js, index.js, migrations/20200913141937_create_user_table.js, package-lock.json, package.json, seeds/01_users.js, src/app.ts, src/controllers/profileController.ts, src/schema/api.json, test/v1/profile/profileController.spec.js
По #23 улучшение
- Улучшил поиск пользоватлей по нескольким словам в запросе
- Добавил CORS, чтобы не ругался при тестирование API с frontend
- Добавил User Seed генерацию людей при помощи faker библиотеки (оставил первого юзера не тронутым если на него есть тесты)
=> feat: find profiles volume 2

CONTRIBUTING.md, config.js
В любой конфигурации, если в env есть переменная DATABASE -
использовать ее.
drive-by: мини инструкция о миграция на проде.
=> infra(config): больше приоритета connection string из env

migrations/20200922001300_update_user_skill.js, package-lock.json, seeds/01_users.js, src/controllers/profileController.ts, src/schema/api.json, test/v1/profile/profileController.spec.js
Перезалив улучшеного поиска по скиллам из-за проблем с предидущий PR
=> feat(search_profile): improved skills PR vol2

.github/CODEOWNERS
Файл обладает неприятной особенностью, если гитхабу не нравится
хотя бы один символ, то он игнорирует весь файл. Временно создам
самый простой вариант, со временем добавим больше OWNERS для
отдельных частей.
=> infra(CODEOWNERS): фикс для CODEOWNERS

migrations/20200921225040_create-friend-table.js, seeds/01_users.js, src/app.ts, src/controllers/friendController.ts, src/controllers/profileController.ts, src/schema/api.json, test/v1/friend/friendController.spec.js
#32 #26 #24 
- Добавление в друзья POST /v1/user/friend/:friendId
- Удаление из друзей DELETE /v1/user/friend/:friendId
- Получение списка друзей  /v1/profile/search с параметром onlyFriends = true
=> feat: Добавление в друзья, удаление из друзей, получение списка друзей

docker-compose-ci.yml, docker-compose-dev.yml, seeds/01_users.js, src/app.ts, src/controllers/locationController.ts, src/controllers/usersController.ts, src/schema/api.json, test/v1/location/locationController.spec.js, test/v1/profile/saveUserDetailsController.spec.js
LocationsController использует три таблицы. На данный момент они устанавливаются мануально из script.sql файла в папке миграций. 
Отлимитировал поиск по первому объекту в массиве для уменьшения нагрузки на сервер.
Жду решения от Алексея по поводу автоматической миграции.
SaveUserDetailsController апдейтит данные пользователя: about, contacts (поле ссылки согласно дизайну) и location.
Работа для #21 #22
=> feat: добавлен рут для локаций и сохранения данных пользователя

src/controllers/usersController.ts, src/schema/api.json, test/v1/contact/contactController.spec.js, test/v1/location/locationController.spec.js, test/v1/profile/profileController.spec.js, test/v1/profile/saveUserDetailsController.spec.js
drive-by: minLength: 1 для большинства текстовых полей.
=> feat(user): возможность обновить imagePath

config.js, src/controllers/emailSenderController.ts
Так мы можем указать через окружуние ссылку с частично заполненными
параметрами, например, app.mesto.co?redirect=something&
=> chore(auth): sendMagicLink лишь добавляет параметры к ссылке

CONTRIBUTING.md
- обязательный тест,
- squash до создания PR,
- менять код, только когда без этого никак
Вторые два пункта направлены на то, чтобы мы могли извлекать максимум
из git, в частности - git blame и git bisect.
=> docs(CONTRIBUTING): добавлена пару пунктов по общему стилю PR

src/schema/api.json, src/validator.ts, test/v1/profile/saveUserDetailsController.spec.js
Для проверки пустой строки использовался minlength: 1, но если поле необязаиельное, то для undefined тоже выдавало ошибку, поэтому я добавил валидатор, который проверяет на пустое значение
=> fix: Если строковое поле необязательное, проверять чтоб значение не было равно пустой строке

src/controllers/profileController.ts, test/v1/profile/profileController.spec.js
1.Добавил только возврат imagePath
2. Eslint fix  документ переформатировал
=> Search fix

migrations/20201006135749_contacts_unique_title_url.js, src/controllers/contactController.ts, test/v1/contact/contactController.spec.js, test/v1/users/usersController.spec.js
У заданного пользователя может быть только одна социальная сеть с
заданным именем.
=> fix(contact): добавлена уникальность ownerId + title + url

src/controllers/authController.ts, src/controllers/emailSenderController.ts, src/utils.ts, test/v1/auth/authMagicLinkController.spec.js
Не существует ни одной причины хранить регистрозависимый email.
=> fix: регистронезависимый email

config.js, src/app.ts
- единственный потенциальный клиент API в prod это сайт места.
- нет никакой практической необходимости кешировать ответы API.
=> fix: cors и cache-control

package-lock.json, package.json, seeds/01_users.js, src/controllers/profileController.ts, src/knex.ts, src/search.ts, test/v1/profile/profileController.spec.js
.. используя % и триграммы, но и старый добрый шаблон 'слово%'.
Это позволит нам хорошо искать:
- микроконтроллеры по запросу микро,
- Санкт-Петербург по запросу Санкт.
drive-by: удалил knex-paginate, на данный момент мы его не используем.
=> feat: для последнего слова в запросе, ищем совпадения не только..

src/controllers/profileController.ts, src/search.ts, test/v1/profile/profileController.spec.js
entries: {
data: [...],
total: number
}
=> fix: поиск должен как минимум возвращать total

.eslintrc.js, migrations/20201015101912_user_busy.js, seeds/01_users.js, src/controllers/usersController.ts, src/schema/api.json, src/search.ts, test/v1/profile/profileController.spec.js, test/v1/profile/saveUserDetailsController.spec.js, test/v1/users/usersController.spec.js
Флаг не бывает NULL, значение по умолчанию FALSE.
Методы ниже возвращают флаг вместе со всей остальной информацией:
- GET /v1/user
- GET /v1/users/:id
- POST /v1/proofile/search
Флаг может быть обновлен с помощью PUT /v1/user - временно опциональный,
пока не проверим, что фронтенд всегда его посылает.
=> feat: User.busy флаг

src/schema/api.json, test/v1/databaseController.spec.js
=> feat: /v1/database/getSkills

config.js, package-lock.json, package.json, src/app.ts, src/controllers/databaseController.ts, src/controllers/usersController.ts, src/schema/api.json, test/utils.js, test/v1/adminControllerForTest.spec.js, test/v1/databaseController.spec.js
Метод принимает:
- q, строка, максимальная длина - 15,
- count, число от 1 до 1000, по умолчанию 10.
Возвращает локации, которые указаны у пользователей в формате:
[
{
location: string,
placeId: string
},
...
]
Пара location + placeId уникальна.
=> feat: GET /v1/database/getLocations

config.js, package-lock.json, package.json, src/app.ts, src/controllers/locationController.ts, src/controllers/openlandController.ts, src/schema/api.json, test/v1/openlandController.spec.js
Все методы требует авторизации.
POST /v1/openland/sendCode
Принимает один параметр:
- openland - строка, максимальная длина 64 символов, может быть
как id пользователя, так и его shortname, так и ссылка,
включающая в себя id, либо shortname, так и @shortname -
в тесте есть примеры.
Возвращает: {
codeId: string
}
Время жизни кода - 2 минуты.
POST /v1/openland/verifyCode
Принимает два параметра:
- codeId - значение полученное из предыдущего метода,
- code - строка в 6 символов с кодом верификации.
Методо возвращает 200 только, если все в порядке, во всех остальных
случаях - 401: код истек, неверный пользователь, неверный код.
POST /v1/openland/getUser
Принимает один параметр:
- openland - строка, максимальная длина 64 символов, может быть
как id пользователя, так и его shortname, так и …
=> feat: методы для работы с openland

src/schema/api.json, test/v1/databaseController.spec.js
Достаточно много навыков не помещаются в 15 символов, например,
"ведение переговоров", "управление персоналом".
=> feat: /v1/database/getSkills, q maxLength = 32

src/controllers/databaseController.ts, test/v1/databaseController.spec.js
q в этих методах должен быть регистронезависимым.
=> fix: /v1/database/getSkills и /v1/database/getLocations

src/search.ts, test/v1/searchController.spec.js
Поиск по навыкам должен быть регистронезависимым.
=> fix: /v1/search по skills

.github/workflows/deploy.yaml, package-lock.json, package.json, utils/deploy.js
- должно стартовать на каждый пуш нового тега с версией:
npm version patch|minor|major
git checkout -B master
git push origin master
- вначале необходимо запустить все новые миграции на БД.
=> infra: GitHub Action для загрузки в лямбду

src/controllers/openlandController.ts, test/v1/openlandController.spec.js
+-1 - одна из самых популярных ошибок в программировании и вот опять!
=> fix: openland sendCode должен работать с ссылкой

migrations/20201029115210_user_skills.js, src/controllers/usersController.ts, src/search.ts, test/v1/searchController.spec.js
Находит только если у пользователя есть хотя бы один из перечисленных
навыков.
=> fix: поиск по skills

src/controllers/usersController.ts, src/schema/api.json, test/v1/profile/saveUserDetailsController.spec.js
иначе вызов skills.map для навыков в нижнем регистре все портит.
=> fix: PUT /v1/user skills по умолчанию - пустой массив

src/app.ts, src/controllers/locationController.ts, src/schema/api.json, src/search.ts
Временное (да-да) решение для поиска по стране:
- фронтенд может зарезолвить то, что выбрал пользовать в расширенный
place id, либо перед поиском.
- если у пользователя расширенный placeId и в запросе расширенный,
то поиск по стране заработает.
=> feat: /v1/resolvePlaceId

src/app.ts, src/controllers/emailSenderController.ts, src/controllers/permissionController.ts, src/controllers/usersController.ts, src/enums/permission.ts, src/schema/api.json, src/utils.ts, test/v1/adminUserController.spec.js, test/v1/permissionController.spec.js
Методы нужны для скрипта, который синхронизирует активированных
пользователей в unisender с пользователями в базе соц сети.
addUser{email, fullName}
activateUser{email}
sendInviteLink{email}
=> feat: addUser/activateUser/banUser

migrations/20210213092147_event_add_columns.js, src/controllers/eventController.ts, src/schema/api.json, test/v1/eventController.spec.js
Оба поля обязательны и должны передаваться в v1/event/addEvent и
v1/event/editEvent. Так же оба поля возвращаются для каждого события
в результатах поисках.
v1/event/search принимает категорию в качестве опционального параметра
поиска.
=> feat(event): добавлены category и time_end

migrations/20210111184458_event.js, migrations/20210213092147_event_set_column_link_to_nullable.js, src/controllers/eventController.ts, src/schema/api.json, test/v1/eventController.spec.js
edit link field, delete require and minimal length
add eventType field. Set require and min length
edit test, controller and migration for events
=> adding additional field for events table

migrations/20210524134140_permission_removeoldtokens.js, src/app.ts, src/controllers/emailSenderController.ts, src/schema/api.json
Метод удаляет все просроченные токены для входа. Будем вызывать его время
от времени, чтобы токены не накапливались.
=> feat: added v1/admin/removeOldTokens

src/controllers/emailSenderController.ts
- ограничено количество удаляемых токенов за раз - 500 штук, если мы
будем запускать этот метод достаточно часто, то больше токенов за
раз никогда удалять не придется,
- добавил try/catch на всякий случай.
=> fix: removeOldTokens

src/controllers/emailSenderController.ts, test/v1/auth/authMagicLinkController.spec.js
429 - Too Many Requests (RFC 6585)
=> fix: 429 для слишком частых запросов

src/controllers/eventController.ts, src/schema/api.json, test/v1/eventController.spec.js
add where clause for search event
add test for search title
=> add q-param (search string) in search event route

migrations/20210505092147_event_add_column_place_id.js, src/controllers/eventController.ts, src/schema/api.json, test/v1/eventController.spec.js
add place_id to api.json for add/edit/search
add place_id to eventController
=> add migration for create place_id in event table

migrations/20210915172147_event_add_column_place_id.js, src/controllers/eventController.ts, src/schema/api.json, test/v1/eventController.spec.js
add migration for create location column in event
add condition for location in api (add and edit event)
add location to add and edit function to event controller
add test for location and creator data
=> create column location in event table. add creator_name and creator

migrations/20220128122256_add_permission.js, src/controllers/usersController.ts, src/schema/api.json
Request with a token that includes UPDATEUSER can update any
user profile with userId passed as request param.
=> feat: add a permission that allows to update any user profile

migrations/20221011204132_lead.js, migrations/20221015222747_signup_data.js, package-lock.json, package.json, src/app.ts, src/controllers/contactController.ts, src/controllers/eventController.ts, src/controllers/friendController.ts, src/controllers/usersController.ts, src/emailService.ts, src/enums/permission.ts, src/schema/api.json, src/validator.ts, test/utils.js, test/v1/profile/profileController.spec.js, test/v1/signupData.test.js
POST /v1/signupData/ allows to add signup data, this method creates user with status = awaiting if needed.
POST /v1/signupData/:userId allows to edit signup data for the existing user.
GET /v1/signupData/:usedId allows to get signup data for the existing user.
Please check api.json for the full list of the available fields.
=> feat: added methods to work with signupData
